name: PR Assign

on:
  pull_request:
    # types: [opened, unassigned]

jobs:
  assign:
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh pr edit $NUMBER --add-assignee ${{ github.event.pull_request.user.login }}
        # env:
        #   GH_TOKEN: ${{ github.token }}
        #   GH_REPO: ${{ github.repository }}
        #   NUMBER: ${{ github.event.pull_request.number }}
        #   ASSIGNEE: ${{ github.event.pull_request.user.login }}
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
