name: PR Assign

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  assign:
    runs-on: ubuntu-20.04
    timeout-minutes: 2

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - name: Assign PR assignee
        run: gh pr edit $PR_NUMBER --add-assignee $PR_ASSIGNEE
        env:
          PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
      - name: Assign PR reviewer
        run: gh pr edit $PR_NUMBER --add-reviewer $PR_REVIEWER
        env:
          # TODO: ランダムアサインの処理
          PR_REVIEWER: ${{ github.event.pull_request.user.login }}