name: PR Assign

on:
  pull_request:
    # types: [opened, unassigned]

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}

jobs:
  assign:
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: gh pr edit $PR_NUMBER --add-assignee $PR_ASSIGNEE
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' }}
