name: Create Release Note
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
  TZ: 'Asia/Tokyo'

jobs:
  merge_and_create_release_note:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Merge
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: develop
          destination_branch: main
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      - name: Setup Tag Name
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
      - name: Create Release Note
        run: gh release create $TAG --target main --generate-notes
        env:
          TAG: ${{ env.CURRENT_DATETIME }}
