name: Create Release Note
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
  TZ: 'Asia/Tokyo'

jobs:
  merge_and_create_release_note:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Tag Name
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
      - name: Create Release Pull Request
        run: gh pr create --title "Release $CURRENT_DATETIME" --body "Release $CURRENT_DATETIME" --base main --head develop --assignee $PR_ASSIGNEE
        # TODO: --reviewer $PR_REVIEWER
        env:
            PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
      - name: Auto Merge Release Pull Request
        run: gh pr merge develop --merge --auto
      - name: Create Release Note
        run: gh release create $TAG --target main --generate-notes
        env:
          TAG: ${{ env.CURRENT_DATETIME }}
