name: Create Release Note
on:
  workflow_dispatch:

jobs:
  merge_and_create_release_note:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Tag Name
        run: echo "TODAY=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
      - name: Create Release Note
        run: gh release create ${{ env.TODAY }} --target ${{ github.sha }} --generate-notes
      - name: Merge
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: develop
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
