name: Create Release Note
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
  TZ: 'Asia/Tokyo'

jobs:
  merge_and_create_release_note:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Tag Name
        run: echo "RELEASE_TAG=release/$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
      - name: Create Release Pull Request
        run: gh pr create --title "$RELEASE_TAG" --body "$RELEASE_TAG" --base main --head develop --assignee "$PR_ASSIGNEE"
        # TODO: --reviewer $PR_REVIEWER
        env:
            PR_ASSIGNEE: ${{ github.actor }}
      - name: Auto Merge Release Pull Request
        run: gh pr merge develop --merge --auto
      - name: Create Release Note
        run: gh release create $RELEASE_TAG --target main --generate-notes
