name: Release App
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  confirm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show Release MY_SECRET
        run: echo ${{ secrets.MY_SECRET }}

  releaseA:
    runs-on: ubuntu-20.04
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release1
        run: echo ${{ vars.MY_ENV }}

  releaseB:
    runs-on: ubuntu-20.04
    environment:
      name: Release2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release2
        run: echo ${{ vars.MY_ENV }}

  release1:
    runs-on: ubuntu-20.04
    needs: [confirm]
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release1
        run: echo ${{ vars.MY_ENV }}

  release2:
    runs-on: ubuntu-20.04
    needs: [confirm]
    environment:
      name: Release2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release2
        run: echo ${{ vars.MY_ENV }}

  call_other_workflow:
    needs: [confirm]
    uses: ./.github/workflows/call.yml

  release3:
    runs-on: ubuntu-20.04
    needs: [release1]
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show Release MY_SECRET
        run: echo ${{ secrets.MY_SECRET }}
      - name: Show REPOSITORY_SECRET
        run: echo ${{ secrets.REPOSITORY_SECRET }}

  release4:
    runs-on: ubuntu-20.04
    needs: [release2]
    environment:
      name: Release2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show REPOSITORY_SECRET
        run: echo ${{ secrets.REPOSITORY_SECRET }}
