name: Release App
on:
  workflow_dispatch:

jobs:
  confirm:
    runs-on: ubuntu-20.04
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        run: echo ${{ secrets.MY_SECRET }}

  release:
    needs: [confirm]
    runs-on: ubuntu-20.04
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        run: echo ${{ secrets.MY_SECRET }}