name: Release App
on:
  workflow_dispatch:

jobs:
  runs-on: ubuntu-20.04
  confirm:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show Release
        run: echo ${{ secrets.MY_SECRET }}

  release1:
    needs: [confirm]
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release1
        run: echo ${{ env.MY_EMV }}

  release2:
    needs: [confirm]
    environment:
      name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release2
        run: echo ${{ env.MY_EMV }}
